# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        ficha_medica_file:
            # ¡CORRECCIÓN FINAL AQUÍ! Incluye el segmento '/public/'
            uri_prefix: /base64/public/uploads/fichas_medicas
            # Esta ruta física sigue siendo correcta
            upload_destination: '%kernel.project_dir%/public/uploads/fichas_medicas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
